// Mock data for handymen
export const HANDYMEN = [
    {
      id: '1',
      name: 'John Doe',
      profession: 'Plumber',
      rating: 4.8,
      reviews: 124,
      hourlyRate: 35,
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
      description: 'Professional plumber with 10+ years of experience. Specializing in repairs, installations, and maintenance.',
      categories: ['Plumbing', 'Bathroom', 'Kitchen'],
      completedJobs: 245,
    },
    {
      id: '2',
      name: 'Jane Smith',
      profession: 'Electrician',
      rating: 4.9,
      reviews: 98,
      hourlyRate: 40,
      avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
      description: 'Certified electrician with expertise in residential and commercial wiring. Available for emergencies.',
      categories: ['Electrical', 'Lighting', 'Wiring'],
      completedJobs: 189,
    },
    {
      id: '3',
      name: 'Mike Johnson',
      profession: 'Carpenter',
      rating: 4.7,
      reviews: 87,
      hourlyRate: 38,
      avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
      description: 'Skilled carpenter specializing in custom furniture, cabinets, and woodworking projects.',
      categories: ['Carpentry', 'Furniture', 'Woodwork'],
      completedJobs: 156,
    },
    {
      id: '4',
      name: 'Sarah Williams',
      profession: 'Painter',
      rating: 4.6,
      reviews: 76,
      hourlyRate: 30,
      avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
      description: 'Interior and exterior painter with an eye for detail. Residential and commercial projects.',
      categories: ['Painting', 'Interior', 'Exterior'],
      completedJobs: 132,
    },
    {
      id: '5',
      name: 'David Lee',
      profession: 'Landscaper',
      rating: 4.8,
      reviews: 65,
      hourlyRate: 32,
      avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
      description: 'Professional landscaper offering lawn care, garden design, and outdoor maintenance services.',
      categories: ['Landscaping', 'Garden', 'Outdoor'],
      completedJobs: 118,
    },
  ];
  
  // Service categories
  export const CATEGORIES = [
    { id: '1', name: 'Plumbing', icon: 'water' },
    { id: '2', name: 'Electrical', icon: 'flash' },
    { id: '3', name: 'Carpentry', icon: 'hammer' },
    { id: '4', name: 'Painting', icon: 'color-palette' },
    { id: '5', name: 'Landscaping', icon: 'leaf' },
    { id: '6', name: 'HVAC', icon: 'thermometer' },
    { id: '7', name: 'Cleaning', icon: 'sparkles' },
    { id: '8', name: 'Moving', icon: 'cube' },
  ];